[package]
<<<<<<< HEAD
name = "rust_scraper"
=======
name = "testtest"
>>>>>>> f7f290a (stuff)
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
chrono = "0.4.33"
chrono-tz = "0.8.5"
csv = "1.3.0"
fantoccini = "0.19.3"
headless_chrome = "1.0.9"
reqwest = { version = "0.11.23", features = ["blocking"] }
scraper = "0.18.1"
tokio = "1.35.1"
=======
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
>>>>>>> f7f290a (stuff)
